/**
 * `llmem init` — write the `.llmem/config.toml` stub.
 *
 * Per design/06 § "Per-command specs → commands/init.ts": writer-only in v1
 * — no reader yet, by design. Users get a discoverable file they can edit
 * by hand; future loops will add a precedence-aware reader (config vs. env
 * vs. flags) once that hierarchy is settled (design/06:137 / :311).
 *
 * Behavior:
 *   - Writes the literal `CONFIG_TOML` block (byte-stable, LF line endings)
 *     to `<workspace>/.llmem/config.toml`. Creates the parent directory if
 *     missing.
 *   - Refuses to overwrite an existing file unless `--force` is passed; on
 *     refusal, prints a forward-slash-normalized error to stderr and
 *     exits 1.
 *   - On success, prints `Wrote <forward-slash path>` to stdout.
 */

import * as fs from 'fs/promises';
import * as path from 'path';
import { z } from 'zod';

import { detectWorkspace } from '../workspace';
import type { CommandSpec } from '../registry';

/**
 * Literal stub written by `llmem init`. Byte-exact with the spec block at
 * design/06:296-309. UTF-8, LF line endings, single trailing newline.
 *
 * Exported so tests can string-compare against it without duplicating the
 * literal — keeps source-vs-test drift impossible.
 */
export const CONFIG_TOML =
    '# .llmem/config.toml\n' +
    '# This file is optional. LLMem works with no config file at all.\n' +
    '# Generated by `llmem init`. Edit freely.\n' +
    '\n' +
    'artifactRoot = ".artifacts"\n' +
    '\n' +
    '[scan]\n' +
    '# Reserved for future use (parser tier per design/01).\n' +
    '\n' +
    '[server]\n' +
    'defaultPort = 3000\n' +
    'openBrowser = true\n';

const initArgs = z.object({
    workspace: z.string().optional()
        .describe('Workspace root directory (auto-detected if omitted)'),
    force: z.boolean().default(false)
        .describe('Overwrite an existing .llmem/config.toml'),
});

export const initCommand: CommandSpec<typeof initArgs> = {
    name: 'init',
    description: 'Write the .llmem/config.toml stub (no-op if it already exists, --force overwrites).',
    examples: [
        { scenario: 'Create the config stub in the current workspace', command: 'llmem init' },
        { scenario: 'Overwrite an existing stub', command: 'llmem init --force' },
    ],
    args: initArgs,
    async run(args) {
        const workspace = detectWorkspace(args.workspace);
        const configPath = path.join(workspace, '.llmem', 'config.toml');
        const dir = path.dirname(configPath);
        const displayPath = configPath.replaceAll('\\', '/');

        // Async existence check (fully async, matches neighbours like
        // `document.ts`). Avoids `existsSync` on the hot path.
        const exists = await fs.stat(configPath).then(() => true, () => false);
        if (exists && !args.force) {
            console.error(
                `Error: ${displayPath} already exists. Use --force to overwrite.`,
            );
            process.exit(1);
        }

        await fs.mkdir(dir, { recursive: true });
        await fs.writeFile(configPath, CONFIG_TOML, 'utf8');
        console.log(`Wrote ${displayPath}`);
    },
};
